[project]
name = "ai-yolo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "numpy>=1.24.0,<2.0",
    "opencv-python==4.11.0.86",
    "pandas==2.3.3",
    "pillow==12.0.0",
    "pyqt6==6.10.0",
    "ruff==0.14.6",
    "ultralytics==8.3.230",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "pytest==9.0.1",
]

[tool.uv]
add-bounds = "exact"

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
